# Generated by Django 5.1.5 on 2025-01-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ кофе', 'verbose_name_plural': 'Заказы кофе'},
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='address',
            field=models.TextField(verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='coffee_type',
            field=models.CharField(max_length=100, verbose_name='Тип кофе'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='coffeeorder',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
