# Generated by Django 5.1.5 on 2025-01-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_coffeeorder_options_alter_coffeeorder_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='coffee_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
            },
        ),
    ]
